custom:
  db:
    url: jdbc:mysql://database-2.cducnzmmkuvl.ap-northeast-2.rds.amazonaws.com:3306/comm?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    usr: ENC(plDde76MscNwKMt9v4A6Rw==)
    pw: ENC(OH+qshDPtFh1h1gDdWExzz/t0BlOzVbo)

  feign:
    study: http://study:8082/pub/study/api/study

  jpa:
    ddl-auto: update


spring:
  config:
    activate:
      on-profile: prod