custom:
  mapping:
    post:
      web: /web/post
    member:
      web: /web/member

  jwt:
    secret-key: ENC(+GbV3Ykx/t5XFlaFHBZnXTzsSf9b3YChS2cVPTvCgwQmevtbB1Hfw91VMC/fTizxVssJvYiAMeQICsuoSrH5zNLh/jxJsXq/)

  db:
    host: localhost
    db: community
    usr: ENC(XdP7alZ9UNQG7MsDRJgGJA==)
    pw: ENC(XdP7alZ9UNQG7MsDRJgGJA==)

server:
  port: 8086


spring:
  profiles:
    default: dev

  data:
    mongodb:
      host: ${custom.db.host}
      port: 27017
      authentication-database: admin
      database: ${custom.db.db}
      username: ${custom.db.usr}
      password: ${custom.db.pw}

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password:

---

spring:
  config:
    activate:
      on-profile: dev