custom:
  mapping:
    base:
      public: /pub/comm
      user: /usr/comm

    post:
      web_pub: ${custom.mapping.base.public}/web/post
      web_usr: ${custom.mapping.base.user}/web/post
    mission:
      web_pub: ${custom.mapping.base.public}/web/mission
      api: ${custom.mapping.base.public}/api/mission
    comment:
      web_usr: ${custom.mapping.base.user}/web/comment

  jwt:
    secret-key: ENC(+GbV3Ykx/t5XFlaFHBZnXTzsSf9b3YChS2cVPTvCgwQmevtbB1Hfw91VMC/fTizxVssJvYiAMeQICsuoSrH5zNLh/jxJsXq/)

  db:
    url: jdbc:mysql://127.0.0.1:3306/bk__comm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    usr: ENC(MrlF9UZUaHufCgWLRE3ipQ==)
    pw: ENC(dhw6nRBS+50xHhqPVFnZdw==)

  jpa:
    ddl-auto: create

server:
  port: 8086


spring:
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${custom.db.url}
    username: ${custom.db.usr}
    password: ${custom.db.pw}
    hikari:
      maximum-pool-size: 51
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: ${custom.jpa.ddl-auto}
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password:

---

spring:
  config:
    activate:
      on-profile: dev