custom:
  jwt:
    secret-key: ENC(+GbV3Ykx/t5XFlaFHBZnXTzsSf9b3YChS2cVPTvCgwQmevtbB1Hfw91VMC/fTizxVssJvYiAMeQICsuoSrH5zNLh/jxJsXq/)

server:
  port: 8086


spring:
  profiles:
    default: dev

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: